name: Build & Test 
on: 
  push:
    branches: [dev]
env:
  DOTNET_VERSION: ${{secrets.DOTNET_VERSION}}
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Display dotnet variable version
        run: echo "The variable version is $DOTNET_VERSION"

