name: Build & Test
on: 
  push:
    branches: [dev]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment variable
        run: echo "DOTNET_VERSION=${{ secrets.DOTNET_VERSION }}" >> $GITHUB_ENV

      - name: Display DOTNET VARIABLE info
        run: echo "Value => $DOTNET_VERSION"

